# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole Tools, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: LatticeMage
email: latticemage@gmail.com
url: https://lattice.posetmage.com # the base hostname & protocol for your site, e.g. http://example.com

description: Tools
baseurl: /Tools # the subpath of your site, e.g. /Tools
repository: latticemage/Tools

exclude:
  - Productivity/Converter/EPUB/book1/
  - _includes/.git/
  - _layouts/.git/
  - _layouts/page/.git/
  - assets/.git/


defaults:
  -
    scope:
      path: ""
    values:
      layout: "page/note/basic"


kramdown:
  parse_block_html: true
  
collections:
  directories:
    output: true


# Build settings
remote_theme: jekyll/minima



minima:
  skin: dark

plugins:
  - jekyll-external-links
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-category-pages
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
