# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the NGINX configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports 80 and 443 for HTTP and HTTPS traffic
EXPOSE 80
EXPOSE 443
